-- Pratica.dev 2.0 — banco de dados Supabase/PostgreSQL
-- Execute este arquivo no SQL Editor de um projeto novo.
-- A chave service_role nunca deve ser usada no frontend.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 2 and 120),
  age integer not null check (age between 10 and 120),
  email text not null,
  level integer not null default 1 check (level >= 1),
  xp integer not null default 0 check (xp >= 0),
  track text,
  goal text,
  quiz_done boolean not null default false,
  is_admin boolean not null default false,
  portfolio_public boolean not null default false,
  avatar_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.quiz_answers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  question integer not null check (question between 1 and 3),
  answer text not null,
  created_at timestamptz not null default now(),
  unique (user_id, question)
);

create table if not exists public.projects (
  id integer primary key,
  name text not null,
  level text not null,
  description text not null,
  xp_reward integer not null default 100 check (xp_reward >= 0)
);

create table if not exists public.subject_progress (
  user_id uuid not null references public.profiles(id) on delete cascade,
  subject_id text not null,
  viewed_at timestamptz not null default now(),
  primary key (user_id, subject_id)
);

create table if not exists public.user_projects (
  user_id uuid not null references public.profiles(id) on delete cascade,
  project_id integer not null references public.projects(id),
  completed_at timestamptz not null default now(),
  primary key (user_id, project_id)
);

create table if not exists public.certificates (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  subject_id text not null,
  title text not null,
  issued_at timestamptz not null default now(),
  unique (user_id, subject_id)
);

insert into public.projects (id, name, level, description, xp_reward) values
  (1, 'Calculadora', 'Iniciante', 'Calculadora funcional com operações básicas', 100),
  (2, 'Lista de Tarefas', 'Iniciante', 'Todo list com adicionar, remover e marcar como concluído', 100),
  (3, 'Relógio Digital', 'Iniciante', 'Relógio com hora, data e cronômetro', 100),
  (4, 'Dashboard Analytics', 'Intermediário', 'Painel com gráficos e dados dinâmicos', 150),
  (5, 'Sistema de Login', 'Intermediário', 'Autenticação com rotas protegidas', 150),
  (6, 'Quiz Interativo', 'Intermediário', 'Quiz com pontuação, timer e ranking', 150),
  (7, 'E-commerce', 'Avançado', 'Loja virtual com carrinho, filtros e checkout', 200),
  (8, 'Rede Social', 'Avançado', 'Feed, perfis, posts e interações', 200),
  (9, 'Chat em Tempo Real', 'Avançado', 'Mensagens instantâneas com WebSocket', 200)
on conflict (id) do update set name = excluded.name, level = excluded.level,
  description = excluded.description, xp_reward = excluded.xp_reward;

create index if not exists quiz_answers_user_idx on public.quiz_answers(user_id);
create index if not exists certificates_user_idx on public.certificates(user_id);
create index if not exists profiles_created_idx on public.profiles(created_at desc);

-- Perfil criado automaticamente quando o Auth cria uma conta.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, name, age, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1)),
    greatest(10, least(120, coalesce((new.raw_user_meta_data ->> 'age')::integer, 18))),
    new.email
  ) on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.recalculate_level(value integer)
returns integer language sql immutable as $$
  select greatest(1, floor(value / 100.0)::integer + 1);
$$;

-- Impede que o cliente altere XP/nível diretamente.
-- As funções de premiação abaixo são SECURITY DEFINER e, por isso,
-- rodam como o dono do schema (postgres). Esse caso é liberado aqui:
-- sem essa exceção o trigger reverteria (new.xp := old.xp) todo XP
-- concedido pelo servidor, e o UPDATE terminaria em silêncio, sem
-- erro e sem efeito. O cliente (papel authenticated) continua
-- bloqueado — ele nunca é 'postgres'.
create or replace function public.protect_profile_fields()
returns trigger language plpgsql as $$
begin
  if current_user = 'postgres' then
    return new;
  end if;
  if not (select coalesce(is_admin, false) from public.profiles where id = auth.uid()) then
    new.xp := old.xp;
    new.level := old.level;
    new.is_admin := old.is_admin;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_protect_profile_fields on public.profiles;
create trigger trg_protect_profile_fields before update on public.profiles
for each row execute function public.protect_profile_fields();

create or replace function public.current_is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and is_admin);
$$;

-- Todas as ações abaixo são atômicas e calculam a recompensa no servidor.
create or replace function public.award_quiz_xp(p_answers jsonb, p_track text, p_goal text)
returns void language plpgsql security definer set search_path = public as $$
declare uid uuid := auth.uid();
begin
  if uid is null then raise exception 'Não autenticado'; end if;
  insert into public.quiz_answers (user_id, question, answer)
  select uid, (row_number() over ())::integer, value::text
  from jsonb_array_elements_text(coalesce(p_answers, '[]'::jsonb)) value
  on conflict (user_id, question) do update set answer = excluded.answer;
  update public.profiles set track = p_track, goal = p_goal, quiz_done = true,
    xp = xp + 50, level = public.recalculate_level(xp + 50) where id = uid;
end;
$$;

create or replace function public.award_subject_view_xp(p_subject_id text)
returns void language plpgsql security definer set search_path = public as $$
declare uid uuid := auth.uid();
begin
  if uid is null then raise exception 'Não autenticado'; end if;
  if not exists (select 1 from public.subject_progress where user_id=uid and subject_id=p_subject_id) then
    insert into public.subject_progress(user_id, subject_id) values (uid, p_subject_id);
    update public.profiles set xp=xp+10, level=public.recalculate_level(xp+10) where id=uid;
  end if;
end;
$$;

create or replace function public.award_exercise_xp(p_subject_id text, p_cert_title text)
returns void language plpgsql security definer set search_path = public as $$
declare uid uuid := auth.uid();
begin
  if uid is null then raise exception 'Não autenticado'; end if;
  insert into public.certificates(user_id, subject_id, title) values(uid,p_subject_id,p_cert_title)
    on conflict (user_id, subject_id) do nothing;
  if found then
    update public.profiles set xp=xp+30, level=public.recalculate_level(xp+30) where id=uid;
  end if;
end;
$$;

create or replace function public.award_project_xp(p_project_id integer)
returns void language plpgsql security definer set search_path = public as $$
declare uid uuid := auth.uid(); reward integer;
begin
  if uid is null then raise exception 'Não autenticado'; end if;
  select xp_reward into reward from public.projects where id=p_project_id;
  if reward is null then raise exception 'Projeto inexistente'; end if;
  insert into public.user_projects(user_id, project_id) values(uid,p_project_id) on conflict do nothing;
  if found then update public.profiles set xp=xp+reward, level=public.recalculate_level(xp+reward) where id=uid; end if;
end;
$$;

create or replace function public.admin_reset_xp(target_id uuid)
returns void language plpgsql security invoker as $$
begin
  if not public.current_is_admin() then raise exception 'Acesso negado'; end if;
  update public.profiles set xp=0, level=1 where id=target_id;
end;
$$;

create or replace function public.admin_delete_student(target_id uuid)
returns void language plpgsql security invoker as $$
begin
  if not public.current_is_admin() then raise exception 'Acesso negado'; end if;
  delete from public.profiles where id=target_id and id <> auth.uid();
end;
$$;

-- RLS: o aluno lê/escreve somente seu próprio contexto; dados de catálogo são públicos.
alter table public.profiles enable row level security;
alter table public.quiz_answers enable row level security;
alter table public.projects enable row level security;
alter table public.subject_progress enable row level security;
alter table public.user_projects enable row level security;
alter table public.certificates enable row level security;

drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles for select using (id=auth.uid() or public.current_is_admin());
drop policy if exists profiles_insert on public.profiles;
create policy profiles_insert on public.profiles for insert with check (id=auth.uid());
drop policy if exists profiles_update on public.profiles;
create policy profiles_update on public.profiles for update using (id=auth.uid() or public.current_is_admin()) with check (id=auth.uid() or public.current_is_admin());

drop policy if exists quiz_select on public.quiz_answers;
create policy quiz_select on public.quiz_answers for select using (user_id=auth.uid() or public.current_is_admin());
drop policy if exists quiz_insert on public.quiz_answers;
create policy quiz_insert on public.quiz_answers for insert with check (user_id=auth.uid());
drop policy if exists quiz_update on public.quiz_answers;
create policy quiz_update on public.quiz_answers for update using (user_id=auth.uid());
drop policy if exists projects_select on public.projects;
create policy projects_select on public.projects for select using (true);
drop policy if exists progress_select on public.subject_progress;
create policy progress_select on public.subject_progress for select using (user_id=auth.uid() or public.current_is_admin());
drop policy if exists projects_user_select on public.user_projects;
create policy projects_user_select on public.user_projects for select using (user_id=auth.uid() or public.current_is_admin());
drop policy if exists certificates_select on public.certificates;
create policy certificates_select on public.certificates for select using (user_id=auth.uid() or public.current_is_admin());
-- award_exercise_xp insere o certificado do próprio aluno. Sem esta
-- política (e sem o grant de INSERT abaixo) o RLS barra a escrita e o
-- exercício nunca emite certificado nem concede os 30 XP.
drop policy if exists certificates_insert on public.certificates;
create policy certificates_insert on public.certificates for insert with check (user_id=auth.uid());

-- RPCs são expostos ao cliente, mas a autorização ocorre dentro das funções.
grant usage on schema public to anon, authenticated;
grant select on public.projects to anon, authenticated;
grant select, insert, update on public.profiles, public.quiz_answers to authenticated;
grant select on public.subject_progress, public.user_projects to authenticated;
grant select, insert on public.certificates to authenticated;
grant execute on all functions in schema public to authenticated;

-- ============================================================
-- PORTFÓLIO PÚBLICO (incremental)
-- ------------------------------------------------------------
-- Em instalações EXISTENTES execute este bloco no SQL Editor;
-- em instalações novas ele é redundante (as colunas já estão no
-- CREATE TABLE acima) e seguro. Também há uma versão destacada em
-- database/migracao-portfolio-avatar.sql.
--
-- Regra: quem tem portfolio_public = true pode ter o perfil, os
-- projetos concluídos e os certificados lidos SEM login (papel
-- anon). As colunas sensíveis (email, age, is_admin) NÃO são
-- concedidas ao papel anon — o grant é por coluna, então nem o
-- cliente nem um atacante com a chave anon conseguem lê-las.
-- ============================================================

alter table public.profiles add column if not exists portfolio_public boolean not null default false;

-- Leitura anônima de perfis publicados (só as linhas públicas).
drop policy if exists profiles_public_read on public.profiles;
create policy profiles_public_read on public.profiles
  for select to anon
  using (portfolio_public = true);

-- Leitura anônima de projetos concluídos de quem publicou o portfólio.
drop policy if exists user_projects_public_read on public.user_projects;
create policy user_projects_public_read on public.user_projects
  for select to anon
  using (user_id in (select id from public.profiles where portfolio_public = true));

-- Leitura anônima de certificados de quem publicou o portfólio.
drop policy if exists certificates_public_read on public.certificates;
create policy certificates_public_read on public.certificates
  for select to anon
  using (user_id in (select id from public.profiles where portfolio_public = true));

-- O papel anon só enxerga as colunas necessárias ao portfólio público.
grant select (id, name, track, goal, level, xp, portfolio_public) on public.profiles to anon;
grant select on public.user_projects, public.certificates to anon;

-- ============================================================
-- FOTO DE PERFIL (AVATAR) NO STORAGE (incremental)
-- ------------------------------------------------------------
-- Em instalações EXISTENTES execute este bloco no SQL Editor;
-- em instalações novas (script inteiro) a coluna avatar_url já
-- está no CREATE TABLE acima e todo o restante é idempotente. Há
-- uma versão destacada em database/migracao-portfolio-avatar.sql.
--
-- Convenção de caminho dos arquivos:
--   avatars/<id do usuário>/avatar.jpg  (ou avatar.png)
-- O primeiro segmento do caminho identifica o dono — é isso que
-- as políticas usam para autorizar.
--
-- Privacidade: a foto segue EXATAMENTE a regra do portfólio
-- público. O bucket "avatars" é PRIVADO (public = false), ou
-- seja, nenhuma imagem é servida por URL pública: toda exibição
-- passa por URL assinada, e criar essa URL exige permissão de
-- leitura no storage.objects. A política de leitura consulta
-- profiles.portfolio_public — visitante anônimo (papel anon) só
-- vê a foto de quem publicou o portfólio. Perfil privado = foto
-- inacessível para anônimos, mesmo com o caminho exato do
-- arquivo em mãos.
-- ============================================================

alter table public.profiles add column if not exists avatar_url text;

-- O papel anon também precisa ler avatar_url nos perfis públicos
-- (grant por coluna, sem abrir email/age/is_admin).
grant select (avatar_url) on public.profiles to anon;

-- Bucket privado (public = false). Os limites de 2 MB e de
-- allowed_mimetypes (JPG/PNG) são aplicados SOMENTE quando as
-- colunas correspondentes existirem em storage.buckets — nem
-- todas as versões do Supabase Storage as possuem. A privacidade
-- de fato vem das policies (RLS), não dessas colunas.
-- O frontend valida tipo e tamanho antes do upload como primeira
-- linha de defesa.
do $$
begin
  insert into storage.buckets (id, name, public)
  values ('avatars', 'avatars', false)
  on conflict (id) do update set public = false;

  if exists (select 1 from information_schema.columns
             where table_schema = 'storage' and table_name = 'buckets'
               and column_name = 'file_size_limit') then
    update storage.buckets set file_size_limit = 2097152 where id = 'avatars';
  end if;

  if exists (select 1 from information_schema.columns
             where table_schema = 'storage' and table_name = 'buckets'
               and column_name = 'allowed_mimetypes') then
    update storage.buckets set allowed_mimetypes = '{image/jpeg,image/png}' where id = 'avatars';
  end if;
end $$;

-- O dono faz upload da própria foto (pasta com o seu id).
drop policy if exists avatars_owner_insert on storage.objects;
create policy avatars_owner_insert on storage.objects
  for insert to authenticated
  with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

-- O dono substitui a própria foto.
drop policy if exists avatars_owner_update on storage.objects;
create policy avatars_owner_update on storage.objects
  for update to authenticated
  using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text)
  with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

-- O dono remove a própria foto.
drop policy if exists avatars_owner_delete on storage.objects;
create policy avatars_owner_delete on storage.objects
  for delete to authenticated
  using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

-- Leitura autenticada: a própria foto, sempre; fotos de outros
-- perfis somente se o portfólio deles estiver público.
drop policy if exists avatars_owner_read on storage.objects;
create policy avatars_owner_read on storage.objects
  for select to authenticated
  using (
    bucket_id = 'avatars'
    and (
      (storage.foldername(name))[1] = auth.uid()::text
      or (storage.foldername(name))[1] in (select id::text from public.profiles where portfolio_public = true)
    )
  );

-- Leitura anônima: apenas fotos de quem publicou o portfólio.
drop policy if exists avatars_public_read on storage.objects;
create policy avatars_public_read on storage.objects
  for select to anon
  using (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] in (select id::text from public.profiles where portfolio_public = true)
  );

-- ============================================================
-- CORREÇÃO DO XP NO SERVIDOR (incremental)
-- ------------------------------------------------------------
-- Registrado em 2026-08-20. Sintoma: o aluno concluía quiz,
-- matéria, exercício ou projeto e o XP continuava em 0 — sem
-- nenhuma mensagem de erro na tela.
--
-- Causa: as funções award_* rodavam como SECURITY INVOKER, ou
-- seja, com o papel do próprio aluno. O trigger
-- trg_protect_profile_fields (que existe para impedir que o
-- cliente edite XP à mão) então executava new.xp := old.xp e
-- descartava a premiação. O UPDATE era bem-sucedido, mas não
-- alterava nada — falha silenciosa. Além disso, o INSERT de
-- award_exercise_xp era barrado pelo RLS de certificates, que
-- só tinha política de SELECT.
--
-- Correção (já refletida nos blocos acima deste arquivo):
--   1. protect_profile_fields libera current_user = 'postgres',
--      que é como as funções SECURITY DEFINER se identificam;
--   2. as 4 funções award_* viraram SECURITY DEFINER com
--      search_path fixo em public (evita sequestro de search_path);
--   3. certificates ganhou a política certificates_insert e o
--      grant de INSERT para o papel authenticated.
--
-- As funções admin_* seguem SECURITY INVOKER de propósito: elas
-- se autorizam por current_is_admin() e o trigger já abre exceção
-- para administradores.
--
-- Em instalações NOVAS não há nada a fazer: rodar este arquivo
-- inteiro já aplica tudo. Em instalações EXISTENTES, reexecute o
-- script completo (todos os comandos são idempotentes) ou apenas
-- os blocos citados acima.
--
-- Garantias preservadas (verificadas em PostgreSQL real):
--   - o papel anon não consegue chamar as funções de XP;
--   - um aluno não concede XP nem emite certificado para outro;
--   - UPDATE direto em profiles.xp continua sem efeito;
--   - repetir exercício/projeto não duplica XP.
-- ============================================================
